## Perform the instructions here: 
# https://docs.ros.org/en/humble/Installation/Alternatives/Ubuntu-Development-Setup.html

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install helper packages
  become: true
  ansible.builtin.apt:
    name:
      - software-properties-common
      - curl 
    state: latest

- name: Check for ROS2 repos in apt sources 
  command: /bin/bash -c "grep -q packages.ros.org /etc/apt/sources.list /etc/apt/sources.list.d/*"
  register: ros_repos
  ignore_errors: true

- name: Install ROS2 GPG keys
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
    dest: /usr/share/keyrings/ros-archive-keyring.gpg
    owner: root
    group: root
    mode: 0644
  when: ros_repos is failed

- name: Add ROS2 Humble/Iron apt repo
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu jammy main"
  when: ros_repos is failed

- name: Install ROS2 base packages
  become: true
  ansible.builtin.apt:
    name:
      - python3-flake8-blind-except 
      - python3-flake8-builtins 
      - python3-flake8-class-newline 
      - python3-flake8-comprehensions 
      - python3-flake8-deprecated 
      - python3-flake8-import-order 
      - python3-flake8-quotes 
      - python3-pytest-repeat 
      - python3-pytest-rerunfailures
      - ros-humble-ros-core
      - ros-humble-rclpy
      - python3-rosdep2
      - python3-colcon-common-extensions
      - ros-humble-ros2bag 
      - ros-humble-robot-localization
    state: present
    cache_valid_time: 86400